### ISSUE TITLE
Issue #001

### ISSUE THREAD

**Issue by mouri11** [BytesClub/Xplode#1]
Compile time error. Check Screenshot.
![screenshot from 2017-04-02 12-30-59](https://cloud.githubusercontent.com/assets/17742382/24585120/40ac10c6-17a0-11e7-9fae-5e02b7a3cce5.png)

**Comment by RudraNilBasu** [comment]
Compile by [this](https://github.com/BytesClub/Xplode/blob/master/README.md#compile-and-run) :
```
g++ *.cpp  -lGL -lGLU -lglut
```

**Comment by mouri11** [comment]
ok.

**Comment by RudraNilBasu** [comment]
The compiling procedure is updated now.

Compile it by:

```
mkdir bin # if it doesn't exist
make
```

The build files will be at the bin/ folder
- *Rudra Nil Basu*
