### ISSUE TITLE
Player: Shooting

### ISSUE THREAD

**Issue by RudraNilBasu** [BytesClub/Xplode#4]
The player should be able to shoot with spacebar.
The bullet should move at a certain speed in the direction of the movement
of the player at the time it was shot
It should be destroyed if:
* It crosses the gameplay area
* Strikes with someone/something

**Comment by mouri11** [comment]
![screenshot from 2017-04-03 08-25-30](https://cloud.githubusercontent.com/assets/17742382/24594113/61f690a6-1847-11e7-991e-2ce22466644f.png)
Is this about the player not being able to shoot? Also, is it normal that the player pixel will keep moving and move out of the screen if not moved? Comment.

**Comment by RudraNilBasu** [comment]
Yes. Player shooting is not yet implemented. It should shoot whenever
the player presses the Space Bar.

Regarding the player moving out of the screen, the player will die once
he crosses the Red border. The Game over screen is yet to be implemented.

- Rudra
